{ ... }:
{
  flake.modules.nixos.sddm =
    {
      pkgs,
      inputs,
      style,
      ...
    }:
    let
      # No flake/Nix packaging upstream - hand-rolled derivation, same shape as
      # the vesktop-plugins `flake = false` input elsewhere in this repo.
      # theme.conf is fully our own (not a sed-patch of upstream's) since it's a
      # short, plain INI file - simpler to just own it outright, same reasoning as
      # every vendored Lua/QML file in this repo.
      samaritan = pkgs.stdenvNoCC.mkDerivation {
        pname = "samaritan-sddm-theme";
        version = "unstable";
        src = inputs.samaritan-sddm-theme;
        dontBuild = true;
        installPhase = ''
                mkdir -p $out/share/sddm/themes/samaritan
                cp -r . $out/share/sddm/themes/samaritan/
                cp ${./sddm/Main.qml} $out/share/sddm/themes/samaritan/Main.qml
                # Upstream's utils/SystemInfo.js is a static, pre-generated file (per
                # its own "Generated by update-system-info.sh" comment) containing the
                # theme author's own machine - hostname WOLKOON, an AMD Ryzen, CachyOS,
                # none of it ours. Regenerated with this host's real values instead.
                # os_age_seconds is left as the fictional Samaritan-lore "activation
                # age" counter (the README calls this out as deliberately fictional,
                # distinct from the real system fields) - not touched.
                cat > $out/share/sddm/themes/samaritan/utils/SystemInfo.js << 'SYSTEMINFO'
          var os_age_seconds = "5111737";
          var cpu = "Intel Core i5-12500H";
          var hostname = "VICTUS";
          var kernel = "6.18.35";
          var os = "NIXOS";
          var architecture = "X86_64";
          SYSTEMINFO
                cat > $out/share/sddm/themes/samaritan/theme.conf << 'THEMECONF'
          [General]
          background="${style.colors.bg}"
          backgroundImage=${./sddm/wallpaper.png}

          primaryText="${style.colors.fg}"
          secondaryText="${style.colors.fgDim}"
          mutedText="${style.colors.fgMuted}"
          headerText="${style.colors.fgDim}"
          triangleColor="${style.colors.warning}"
          accessGranted="${style.colors.success}"
          accessDenied="${style.colors.error}"
          bootText="${style.colors.fgMuted}"
          onlineText="${style.colors.fg}"

          # Upstream's own bundled fonts (registered system-wide via fonts.packages
          # below) - kept as-is rather than swapped for our usual CaskaydiaCove NFM,
          # since the whole point of this theme is its specific typography.
          mainFont=monoMMM_5
          headerFont=DIN
          samaritanFont=MagdaCleanMono

          passwordFieldWidth=220
          passwordFieldHeight=28
          passwordFieldFontSize=12
          passwordFieldLetterSpacing=1
          passwordCharacter=
          showPasswordButton=false

          passwordFieldOffsetX=0
          passwordFieldOffsetY=50

          selectorSpacing=10
          selectorFontSize=14
          selectorArrowFontSize=17
          selectorHeight=35
          selectorArrowWidth=10
          selectorRadius=10

          showSelectorPreview=true
          selectorPreviewFontSize=13
          selectorPreviewMargin=25

          animationDuration=200
          fadeInDuration=1000

          elementSpacing=15
          elementOpacity=1.0

          showCursor=false

          showHelpTips=false
          helpTipsFontSize=11

          showCapsLockIndicator=true
          capsLockIndicatorFontSize=12

          allowEmptyPassword=false
          clearPasswordOnError=false
          THEMECONF
        '';
      };
    in
    {
      # The UWSM-managed entry (hyprland-uwsm.desktop, shipped automatically by
      # nixpkgs' programs.hyprland.enable alongside plain hyprland.desktop) -
      # not whatever sddm defaults to with nothing set (turned out to be
      # driftwm, confirmed live via `journalctl -u display-manager`), and not
      # plain "hyprland" either anymore: that path's manual graphical-session
      # activation hack (see hyprland.lua/default.nix history) started the
      # target on login but never stopped it on logout, leaving stale systemd
      # session state that broke the next login's session allocation outright -
      # a real hang requiring a hard shutdown. UWSM ties start and stop to the
      # compositor's actual process lifetime instead of a bare exec_cmd call.
      services.displayManager.defaultSession = "hyprland-uwsm";

      # Required by SDDM's Xorg-hosted greeter below - doesn't affect the actual
      # session logged into afterward, still whatever compositor is picked
      # (Hyprland, Wayland-native, XWayland disabled in hyprland.lua).
      services.xserver.enable = true;

      services.displayManager.sddm = {
        enable = true;
        theme = "samaritan";
        # Switched off the native Wayland greeter (the login screen's own
        # renderer) after it shipped with no working touchpad/mouse, keyboard
        # only - a known weak spot in SDDM's still-maturing Wayland greeter, not
        # specific to this theme or this laptop. The Xorg-hosted greeter is the
        # better-tested path and only affects the greeter, not the session
        # logged into afterward.
        wayland.enable = false;
        package = pkgs.kdePackages.sddm; # Qt6 build - avoids missing-cursor/module bugs
        extraPackages = with pkgs.kdePackages; [
          qtsvg
          qtdeclarative
          qt5compat
        ];
      };

      environment.systemPackages = [ samaritan ];

      # Referenced by theme.conf as bare family names (mainFont/headerFont/
      # samaritanFont above) with no FontLoader anywhere in the QML - upstream's
      # own install.sh copies these into ~/.fonts imperatively, which obviously
      # doesn't apply here, so they need registering into the system font
      # database directly for SDDM's greeter to resolve them via fontconfig.
      fonts.packages = [
        (pkgs.stdenvNoCC.mkDerivation {
          pname = "samaritan-sddm-theme-fonts";
          version = "unstable";
          src = inputs.samaritan-sddm-theme + "/assets/fonts";
          dontBuild = true;
          installPhase = ''
            mkdir -p $out/share/fonts/truetype
            cp *.ttf $out/share/fonts/truetype/
          '';
        })
      ];

      # Nix store files all share a fixed mtime, and Qt's QML disk cache is
      # keyed off (path, mtime) - loaded via the stable /run/current-system/sw
      # symlink, every rebuild looks unchanged to it, so the greeter kept
      # running bytecode compiled from Main.qml before any of today's edits
      # (confirmed live: the daemon log showed console.log lines from the
      # avatar code well after that code was deleted from the file on disk).
      # Long-standing, well-documented NixOS+Qt issue, not specific to this
      # theme - nixpkgs uses this exact tmpfiles-wipe pattern for the same bug
      # elsewhere. Runs on every boot and every `nixos-rebuild switch`.
      systemd.tmpfiles.rules = [ "R /var/lib/sddm/.cache" ];
    };
}
