[config]

[templates.browser]
input_path = "~/.config/noctalia/templates/browser.css"
output_path = "~/browser-new-tab/noctalia.css"

[templates.niri]
input_path = "~/.config/noctalia/templates/niri.kdl"
output_path = "~/.config/niri/noctalia.kdl"

[templates.nvim]
input_path = "~/.config/noctalia/templates/nvim.lua"
output_path = "~/.config/nvim/lua/neru/theme.lua"

[templates.vesktop]
input_path = "~/.config/noctalia/templates/vesktop.css"
output_path = "~/.config/vesktop/themes/noctalia.theme.css"
