set-option -g status-position top
set -g status-style bg=default,fg=default

set -g status-left-length 50
set -g status-left "#[fg=blue,bold] #S#[fg=default,nobold],"

set -g status-right "#[fg=default] %H:%M "

set -g status-justify left
setw -g window-status-format "#[fg=colour8] #I:#W "
setw -g window-status-current-format "#[fg=default,bold] #I:#W*"
setw -g window-status-separator ""
