[colors]
bg = "#fafafa"
bgDim = "#eeeeee"
bgAlt = "#dedede"
border = "#b4b4b4"
fg = "#0f0f0f"
fgDim = "#383838"
fgMuted = "#666666"

accent = "#262626"
error = "#3a3a3a"
warning = "#5a5a5a"
success = "#484848"
info = "#525252"

black = "#1a1a1a"
brightBlack = "#666666"
red = "#3a3a3a"
brightRed = "#2a2a2a"
green = "#4a4a4a"
brightGreen = "#383838"
yellow = "#5a5a5a"
brightYellow = "#474747"
blue = "#404040"
brightBlue = "#303030"
magenta = "#505050"
brightMagenta = "#3e3e3e"
cyan = "#545454"
brightCyan = "#424242"
white = "#6e6e6e"
brightWhite = "#808080"

[fonts]
mono = "GeistMono Nerd Font Mono"
size = 18
sizeUi = 11

[ui]
radius = 12
