#!/usr/bin/env python3
import glob
import json
import os
import re
import subprocess
import sys
import time
import tomllib
from pathlib import Path

HEX_RE = re.compile(r"^#([0-9a-fA-F]{6})$")
TOKEN_RE = re.compile(r"\{\{(\w+)\}\}")

CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
ENGINE_DIR = CONFIG_HOME / "theme-engine"
THEMES_DIR = ENGINE_DIR / "themes"
TEMPLATES_DIR = ENGINE_DIR / "templates"
APPS_FILE = ENGINE_DIR / "apps.json"
CURRENT_FILE = ENGINE_DIR / "current"
# User overrides that survive theme switches (written by `theme-set font`).
# Only the [fonts] section is merged over the selected theme - colors stay
# strictly theme-owned.
OVERRIDES_FILE = ENGINE_DIR / "overrides.toml"
DEFAULT_THEME = "mocha"

# Every template may rely on any of these, so a theme that omits one would
# leave literal {{token}} text in rendered configs.
REQUIRED_TOKENS = [
    # [colors]
    "bg",
    "bgDim",
    "bgAlt",
    "bgOverlay",
    "border",
    "fg",
    "fgDim",
    "fgMuted",
    "accent",
    "error",
    "warning",
    "success",
    "info",
    "red",
    "orange",
    "cyan",
    "blue",
    # [fonts]
    "mono",
    "size",
    # [misc]
    "radius",
]

def warn(msg: str) -> None:
    # Loud only when run from a terminal: Home Manager activation and
    # keybind spawns must stay quiet and must never fail on a warning.
    if sys.stderr.isatty():
        print(f"theme-set: warning: {msg}", file=sys.stderr)


def load_apps() -> dict[str, dict]:
    # Generated by Home Manager from the theme-engine.apps option - the
    # registry lives in Nix, so wiring up a new app only touches its module.
    if not APPS_FILE.is_file():
        sys.exit(f"theme-set: {APPS_FILE} not found (Home Manager not activated?)")
    return json.loads(APPS_FILE.read_text())


def load_overrides() -> dict:
    if not OVERRIDES_FILE.is_file():
        return {}
    try:
        return tomllib.loads(OVERRIDES_FILE.read_text())
    except tomllib.TOMLDecodeError as error:
        warn(f"ignoring {OVERRIDES_FILE}: {error}")
        return {}


def load_theme(name: str) -> dict[str, str]:
    theme_file = THEMES_DIR / f"{name}.toml"
    if not theme_file.is_file():
        sys.exit(f"theme-set: unknown theme '{name}' ({theme_file} not found)")
    data = tomllib.loads(theme_file.read_text())
    # Merged before token derivation so derived values (sizeLarge, dconf
    # font strings, ...) all flow from the override naturally.
    font_overrides = load_overrides().get("fonts", {})
    if font_overrides:
        data.setdefault("fonts", {}).update(font_overrides)
    tokens: dict[str, str] = {}
    for section in data.values():
        for key, value in section.items():
            value = str(value)
            tokens[key] = value
            hex_match = HEX_RE.match(value)
            if hex_match:
                r = int(hex_match.group(1)[0:2], 16)
                g = int(hex_match.group(1)[2:4], 16)
                b = int(hex_match.group(1)[4:6], 16)
                # Derived Qt-style AARRGGBB token (opaque) for consumers that need it, e.g. qt5ct/qt6ct.
                tokens[key + "Argb"] = "ff" + hex_match.group(1)
                # Derived 0-1 float triplet for consumers that need it, e.g. GLSL vec3 literals.
                tokens[key + "Glsl"] = f"{r / 255:.3f}, {g / 255:.3f}, {b / 255:.3f}"
                # Derived 0-255 int triplet for consumers that need it, e.g. CSS rgba().
                tokens[key + "Rgb"] = f"{r}, {g}, {b}"
                # Derived 20%-toward-white variant for consumers that need a hover/lighter shade.
                lr, lg, lb = (round(c * 0.8 + 255 * 0.2) for c in (r, g, b))
                tokens[key + "Light"] = f"#{lr:02x}{lg:02x}{lb:02x}"
    missing = [t for t in REQUIRED_TOKENS if t not in tokens]
    if missing:
        sys.exit(f"theme-set: theme '{name}' is missing required keys: {', '.join(missing)}")
    # Derived larger sizes for sparse full-screen UIs (tofi chrome and
    # headings) that want more presence than the terminal-ish base size.
    tokens["sizeLarge"] = str(round(float(tokens["size"]) * 1.2))
    tokens["sizeTitle"] = str(round(float(tokens["size"]) * 1.6))
    # radiusScale: a proportional multiplier (1.0 = unchanged), not radius
    # copied verbatim, for consumers with their own global "roundness" scale
    # applied on top of independently-tuned base shapes rather than a single
    # literal radius (Noctalia's shell.corner_radius_scale is exactly this -
    # confirmed via its own source, it multiplies against internal
    # Style::radiusSm/Md/Lg/Xl constants, not against explicit per-component
    # settings like bar.main.radius, so this and {{radius}} itself are safe
    # to use together without double-scaling). 12 is this repo's own
    # reference default (mocha's radius, also Noctalia's own built-in
    # default), so radius=12 themes get scale=1.0 unchanged.
    tokens["radiusScale"] = f"{float(tokens['radius']) / 12:.3f}"
    # barMarginH: a sharp/square theme (radius=0) reads as a deliberate flat,
    # edge-to-edge aesthetic - a floating pill-shaped bar with side margins
    # doesn't fit that language the way it does for rounded themes, so drop
    # the margins entirely rather than leave a rounded-bar-shaped gap on a
    # square theme. 180 matches Noctalia's own default margin_h.
    tokens["barMarginH"] = "0" if float(tokens["radius"]) == 0 else "180"
    return tokens


def render(text: str, tokens: dict[str, str]) -> str:
    for key, value in tokens.items():
        text = text.replace("{{" + key + "}}", value)
    return text


def leftover_tokens(rendered: str) -> list[str]:
    return sorted(set(TOKEN_RE.findall(rendered)))


class ReloadBatch:
    # All reload commands launch concurrently and share one 5s deadline:
    # sequential waits made theme switching visibly laggy (28 kitty CLI
    # spawns alone cost ~700ms back to back), and one app's hung or missing
    # reload binary must not block or abort the others - this is also what
    # makes theme-set safe to call from Home Manager activation, which has
    # a hard timeout on the whole activation script.
    def __init__(self):
        self._procs: list[tuple[subprocess.Popen, list[str]]] = []

    def launch(self, cmd: list[str]) -> None:
        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except FileNotFoundError:
            warn(f"'{cmd[0]}' not found")
            return
        except OSError as error:
            warn(f"'{' '.join(cmd)}' failed to start: {error}")
            return
        self._procs.append((proc, cmd))

    def wait(self, timeout: float = 5.0) -> None:
        deadline = time.monotonic() + timeout
        for proc, cmd in self._procs:
            try:
                code = proc.wait(timeout=max(0.1, deadline - time.monotonic()))
                if code != 0:
                    warn(f"'{' '.join(cmd)}' exited {code}")
            except subprocess.TimeoutExpired:
                proc.kill()
                warn(f"'{' '.join(cmd)}' timed out")


def write_rendered(dest: Path, rendered: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_name(dest.name + ".tmp")
    tmp.write_text(rendered)
    tmp.replace(dest)


def render_to(source_label: str, text: str, tokens: dict[str, str], dest: Path) -> None:
    rendered = render(text, tokens)
    leftover = leftover_tokens(rendered)
    if leftover:
        warn(f"{source_label}: unreplaced tokens: {', '.join(leftover)}")
    write_rendered(dest, rendered)


def reload_kitty(batch: ReloadBatch, dest: Path) -> None:
    # Every kitty invocation is its own process, each
    # listening on its own PID-scoped socket (see kitty's `listen_on`
    # config) - reach every one of them, not just whichever process happened
    # to grab a single shared address first. Two calls, not one: load-config
    # updates kitty's live options (font family/size, border colors, etc -
    # anything read fresh from options each frame), but it does NOT push new
    # colors into a window's already-baked color_profile (background,
    # foreground, cursor, selection, the 16 ANSI colors) - only set-colors
    # does that. Confirmed by testing: without set-colors, background and
    # color0-15 stayed on the old theme after a reload while border colors
    # updated fine.
    for sock in glob.glob("/tmp/kitty-*"):
        # The socket path embeds the owning PID (listen_on kitty-{kitty_pid});
        # closed windows leave their sockets behind, so skip dead ones
        # instead of paying two kitty CLI spawns per corpse.
        pid = sock.rsplit("-", 1)[-1]
        if pid.isdigit() and not Path(f"/proc/{pid}").is_dir():
            continue
        batch.launch(["kitty", "@", "--to", f"unix:{sock}", "load-config"])
        batch.launch(["kitty", "@", "--to", f"unix:{sock}", "set-colors", "-a", "-c", str(dest)])


def apply_theme(name: str) -> None:
    tokens = load_theme(name)
    apps = load_apps()
    # Two passes, not interleaved: an app that reloads one file (its config)
    # can, as a side effect, re-read another. If that second file hasn't been
    # written yet because it's later in the registry, the reload picks up
    # last theme's content instead of this one's - writing everything first
    # before any reload fires closes that race regardless of which apps
    # happen to interact.
    dests: dict[str, Path] = {}
    for app_name, app in apps.items():
        template_path = TEMPLATES_DIR / f"{app_name}.tmpl"
        if not template_path.is_file():
            warn(f"{app_name}: template {template_path} missing, skipped")
            continue
        dest = Path(os.path.expanduser(app["target"]))
        render_to(template_path.name, template_path.read_text(), tokens, dest)
        dests[app_name] = dest
    batch = ReloadBatch()
    for app_name, app in apps.items():
        dest = dests.get(app_name)
        if dest is None:
            continue
        if app_name == "kitty":
            reload_kitty(batch, dest)
        elif app.get("reload"):
            batch.launch(app["reload"])
    font = f"{tokens['mono']} {tokens['size']}"
    # dconf, not gsettings: gsettings needs the compiled schema
    # resolvable via XDG_DATA_DIRS, which isn't reliably true from
    # theme-set's wrapped environment - dconf writes the key directly.
    gvariant = "'" + font.replace("'", "\\'") + "'"
    batch.launch(["dconf", "write", "/org/gnome/desktop/interface/font-name", gvariant])
    batch.launch(["dconf", "write", "/org/gnome/desktop/interface/monospace-font-name", gvariant])
    # GTK4/libadwaita apps follow this portal-visible hint at runtime; GTK3's
    # own dark flag lives in the Nix-managed settings.ini and stays static.
    dark = tokens.get("dark", "true").strip().lower() not in ("false", "0")
    scheme = "prefer-dark" if dark else "prefer-light"
    batch.launch(["dconf", "write", "/org/gnome/desktop/interface/color-scheme", f"'{scheme}'"])
    ENGINE_DIR.mkdir(parents=True, exist_ok=True)
    CURRENT_FILE.write_text(name + "\n")
    batch.launch(["notify-send", "-a", "theme-set", "Theme applied", name])
    batch.wait()


def list_themes() -> list[str]:
    return sorted(p.stem for p in THEMES_DIR.glob("*.toml"))


def current_theme() -> str:
    if CURRENT_FILE.is_file():
        return CURRENT_FILE.read_text().strip()
    return DEFAULT_THEME


def cycle(step: int) -> None:
    names = list_themes()
    if not names:
        sys.exit(f"theme-set: no themes found in {THEMES_DIR}")
    cur = current_theme()
    idx = names.index(cur) if cur in names else 0
    apply_theme(names[(idx + step) % len(names)])


def font_command(args: list[str]) -> None:
    if not args:
        override = load_overrides().get("fonts", {}).get("mono")
        print(override if override else "(theme default)")
        return
    if args == ["default"]:
        OVERRIDES_FILE.unlink(missing_ok=True)
    else:
        family = " ".join(args)
        ENGINE_DIR.mkdir(parents=True, exist_ok=True)
        OVERRIDES_FILE.write_text(f'[fonts]\nmono = "{family}"\n')
    apply_theme(current_theme())


def main() -> None:
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print("usage: theme-set <name>|list|current|next|prev|reapply|font [<family>|default]")
        return
    cmd = args[0]
    if cmd == "list":
        cur = current_theme()
        for name in list_themes():
            print(("* " if name == cur else "  ") + name)
    elif cmd == "current":
        print(current_theme())
    elif cmd == "next":
        cycle(1)
    elif cmd == "prev":
        cycle(-1)
    elif cmd == "reapply":
        # Re-apply the current theme (seeding the default on first run) -
        # used by Home Manager activation so a rebuild keeps the live theme.
        apply_theme(current_theme())
    elif cmd == "font":
        font_command(args[1:])
    else:
        apply_theme(cmd)


if __name__ == "__main__":
    main()
